baseURL = "/"
languageCode = "en-us"
theme = "terminal"
title = "λ Guillaume Bogard"

[params]
  themeColor = "pink"
  fullWidthTheme = false
  centerTheme = false
  readMore = "Read more"
  [params.logo]
    logoText = "Guillaume Bogard"

[taxonomies]
  category = "categories"
  tag = "tags"
  tools = "tools"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"
[[menu.main]]
  identifier = "resume"
  name = "Résumé"
  url = "/jobs"