baseURL = "/"
languageCode = "en-gb"
theme = "terminal"
title = "λ Guillaume Bogard"
ignoreFiles = [
  '\.*experience.md'
]

[params]
  themeColor = "pink"
  fullWidthTheme = false
  centerTheme = true
  readMore = "Read more"
  [params.logo]
    logoText = "λ Guillaume Bogard"

[markup.goldmark.renderer]
unsafe=true

[markup.highlight]
  noClasses = false
  style = "algol"

[taxonomies]
  category = "categories"
  tag = "tags"
  tools = "tools"

[[menu.main]]
  identifier = "home"
  name = "About me"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "resume"
  name = "Résumé"
  url = "/resume"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"
[[menu.main]]
  identifier = "videos"
  name = "Videos"
  url = "/videos"
